# Generated by Django 5.1.3 on 2024-12-20 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Canteen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('region', models.TextField(blank=True, choices=[('01', '01 - Guadeloupe'), ('02', '02 - Martinique'), ('03', '03 - Guyane'), ('04', '04 - La Réunion'), ('06', '06 - Mayotte'), ('11', '11 - Île-de-France'), ('24', '24 - Centre-Val de Loire'), ('27', '27 - Bourgogne-Franche-Comté'), ('28', '28 - Normandie'), ('32', '32 - Hauts-de-France'), ('44', '44 - Grand Est'), ('52', '52 - Pays de la Loire'), ('53', '53 - Bretagne'), ('75', '75 - Nouvelle-Aquitaine'), ('76', '76 - Occitanie'), ('84', '84 - Auvergne-Rhône-Alpes'), ('93', "93 - Provence-Alpes-Côte d'Azur"), ('94', '94 - Corse')], null=True, verbose_name='région')),
                ('city', models.TextField(blank=True, null=True, verbose_name='ville')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='code postal')),
                ('daily_meal_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='repas par jour')),
                ('admins', models.ManyToManyField(related_name='canteens', to=settings.AUTH_USER_MODEL)),
                ('consumers', models.ManyToManyField(related_name='consumer_canteens', to=settings.AUTH_USER_MODEL, verbose_name='Consommateurs')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(related_name='notes', to='api.category')),
            ],
        ),
    ]
