# Generated by Django 5.1.3 on 2024-12-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('djf_surveys', '0017_alter_survey_success_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteen',
            name='relatedSurveys',
            field=models.ManyToManyField(blank=True, related_name='surveys', to='djf_surveys.survey'),
        ),
    ]
