# Generated by Django 5.1.3 on 2024-12-16 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_survey_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Canteen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('region', models.TextField(blank=True, null=True, verbose_name='région')),
                ('city', models.TextField(blank=True, null=True, verbose_name='ville')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='code postal')),
                ('daily_meal_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='repas par jour')),
                ('admins', models.ManyToManyField(related_name='canteens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyCanteen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canteen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_canteens', to='api.canteen')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_canteens', to='api.survey')),
            ],
        ),
    ]
