# Generated by Django 5.1.3 on 2024-12-16 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_canteen_surveycanteen'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='cantine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='api.canteen'),
        ),
    ]
