# Generated by Django 5.1.3 on 2024-12-17 08:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_surveyresponse_cantine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='canteen',
            name='consumers',
            field=models.ManyToManyField(related_name='consumer_canteens', to=settings.AUTH_USER_MODEL, verbose_name='Consommateurs'),
        ),
        migrations.AlterField(
            model_name='canteen',
            name='region',
            field=models.TextField(blank=True, choices=[('01', '01 - Guadeloupe'), ('02', '02 - Martinique'), ('03', '03 - Guyane'), ('04', '04 - La Réunion'), ('06', '06 - Mayotte'), ('11', '11 - Île-de-France'), ('24', '24 - Centre-Val de Loire'), ('27', '27 - Bourgogne-Franche-Comté'), ('28', '28 - Normandie'), ('32', '32 - Hauts-de-France'), ('44', '44 - Grand Est'), ('52', '52 - Pays de la Loire'), ('53', '53 - Bretagne'), ('75', '75 - Nouvelle-Aquitaine'), ('76', '76 - Occitanie'), ('84', '84 - Auvergne-Rhône-Alpes'), ('93', "93 - Provence-Alpes-Côte d'Azur"), ('94', '94 - Corse')], null=True, verbose_name='région'),
        ),
    ]
