# Generated by Django 5.1.3 on 2024-12-02 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_category_note_tags_delete_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='tags',
            new_name='categories',
        ),
    ]
